(function(){'use strict';
var VERSION='0.4.0',API='https://api.yani.tv',APP='p6_gpujl6d3pho8n',POLL=60000,CACHE={};
function req(path,ttl){var c=CACHE[path];if(ttl&&c&&Date.now()-c.at<ttl)return Promise.resolve(c.data);return fetch(API+path,{headers:{'X-Application':APP,Accept:'application/json',Lang:'ru'}}).then(function(r){if(!r.ok)throw Error('API '+r.status);return r.json()}).then(function(x){CACHE[path]={at:Date.now(),data:x};return x})}
function root(p){return p&&p.response!==undefined?p.response:p}
function arr(p){var r=root(p);return Array.isArray(r)?r:(r&&(r.anime||r.results||r.items||r.data))||[]}
function val(o,k){for(var i=0;i<k.length;i++){var x=o&&o[k[i]];if(x!==undefined&&x!==null&&x!=='')return x}return ''}
function id(x){return val(x,['anime_id','animeId','id'])||(x&&x.anime&&val(x.anime,['anime_id','id']))}
function title(x){return val(x,['title','anime_title','title_ru','name','russian','title_en'])||(x&&x.anime&&title(x.anime))||'Без названия'}
function poster(x){var p=val(x,['poster','image','img','cover']);if(!p&&x&&x.anime)p=poster(x.anime);if(p&&typeof p==='object')p=val(p,['huge','mega','big','large','fullsize','full','medium','small','original','url']);p=String(p||'');return p.indexOf('//')===0?'https:'+p:p}
function card(x){return {title:title(x),name:title(x),poster:poster(x),img:poster(x),release_date:val(x,['year','release_year']),yani_id:id(x),yani_raw:x}}
function note(x){if(Lampa.Noty)Lampa.Noty.show(x)}
function sel(t,items,cb){Lampa.Select.show({title:t,items:items,onSelect:cb,onBack:function(){Lampa.Controller.toggle('content')}})}
function vlist(p){var r=root(p);return Array.isArray(r)?r:(r&&(r.videos||r.items))||[]}
function vdata(v){var d=v&&v.data||{};if(typeof d==='string')try{d=JSON.parse(d)}catch(e){d={}}return d||{}}
function voice(v){var d=vdata(v);return d.dubbing||d.translation||d.voice||v.dub_title||v.dubbing||'Без указания озвучки'}
function source(v){var d=vdata(v);return d.player||v.player_title||v.player||d.player_id||'Источник'}
function ep(v){return String(v.number||v.episode||v.index||v.ep_title||'?')}
function sourceUrl(v){var d=vdata(v);return v.yani_stream_url||v.stream_url||v.file||v.src||v.iframe_url||v.player_url||v.url||v.link||d.yani_stream_url||d.stream_url||d.file||d.src||d.iframe_url||d.player_url||d.url||d.link||''}
function direct(u){return /\.(m3u8|mpd|mp4|webm)(?:[?#].*)?$/i.test(String(u||''))}
function playDirect(c,v,u){var list=[{url:u,title:c.title+' · '+ep(v)+' серия'}];Lampa.Player.play(list[0]);Lampa.Player.playlist(list)}
function play(c,v){var u=sourceUrl(v);if(!u)return note('У источника нет ссылки на видео');if(direct(u))return playDirect(c,v,u);
 /* Reuse an installed resolver when available; Anime Lite does not copy YummyAnime's unlicensed resolver implementation. */
 if(window.LampaYaniStreamResolver&&LampaYaniStreamResolver.canResolve&&LampaYaniStreamResolver.canResolve(u)){note('Подготавливаю поток…');return LampaYaniStreamResolver.resolve(u,v).then(function(r){if(r&&r.url)return playDirect(c,v,r.url);note('Не удалось получить поток')}).catch(function(){note('Источник «'+source(v)+'» сейчас не удалось открыть')})}
 note('Источник «'+source(v)+'» не отдаёт прямой поток')}
function openVideos(c){note('Загружаю серии…');req('/anime/'+encodeURIComponent(c.yani_id)+'/videos').then(function(p){var a=vlist(p);if(!a.length)return note('Для этого аниме пока нет видео');var g={};a.forEach(function(v){var k=voice(v)+'|'+source(v);if(!g[k])g[k]={title:voice(v),player:source(v),videos:[]};g[k].videos.push(v)});var voices=Object.keys(g).map(function(k){var x=g[k];return {title:x.title+(x.player!==x.title?' · '+x.player:''),subtitle:x.videos.length+' серий',group:x}});sel('Озвучка · '+c.title,voices,function(ch){var vs=ch.group.videos.slice().sort(function(a,b){return parseFloat(ep(a))-parseFloat(ep(b))});var seen={},episodes=vs.filter(function(v){var k=ep(v);if(seen[k])return false;seen[k]=1;return true}).map(function(v){return {title:'Серия '+ep(v)+(v.quality?' · '+v.quality:''),video:v}});if(episodes.length===1)return play(c,episodes[0].video);sel(ch.title,episodes,function(e){play(c,e.video)})})}).catch(function(e){console.error(e);note('Не удалось загрузить видео')})}
function openDetail(c){note('Загружаю карточку…');req('/anime/'+encodeURIComponent(c.yani_id),30000).then(function(p){var d=root(p)||c.yani_raw||{},items=[{title:'▶ Смотреть',action:'watch'}];var desc=val(d,['description','overview','summary']);var year=val(d,['year','release_year']);var status=val(d,['status','status_title']);if(year||status)items.push({title:[year,status].filter(Boolean).join(' · '),disabled:true});if(desc)items.push({title:String(desc).replace(/<[^>]+>/g,' ').slice(0,180),disabled:true});sel(c.title,items,function(x){if(x.action==='watch')openVideos(c)})}).catch(function(){openVideos(c)})}
function row(name,items){var seen={};return {title:name,results:(items||[]).map(card).filter(function(c){var k=String(c.yani_id||'');if(!k||seen[k])return false;seen[k]=1;return true}).slice(0,20),nomore:true,card_events:{onEnter:function(t,c){openDetail(c)}}}}
function feedRows(feed,catalog,schedule){var f=root(feed)||{},nw=Array.isArray(f.new)?f.new:[],vv=Array.isArray(f.new_videos)?f.new_videos:[],cols=Array.isArray(f.collections)?f.collections:[],latest=vv.map(function(x){return x.anime&&typeof x.anime==='object'?Object.assign({},x.anime,{anime_id:id(x),title:title(x),poster:poster(x)}):x}),rows=[row('Новые релизы',nw.length?nw:catalog),row('Новые переводы',latest),row('Сейчас выходит',arr(schedule))];if(cols.length){var ca=[];cols.forEach(function(x){(x.animes||[]).slice(0,8).forEach(function(a){ca.push(a)})});if(ca.length)rows.push(row('Подборки',ca))}return rows.filter(function(x){return x.results.length})}
function loadRows(fresh){if(fresh){delete CACHE['/feed'];delete CACHE['/anime?limit=20'];delete CACHE['/anime/schedule']}return Promise.all([req('/feed',fresh?0:30000).catch(function(){return {}}),req('/anime?limit=20',fresh?0:30000),req('/anime/schedule',fresh?0:30000)]).then(function(x){return feedRows(x[0],arr(x[1]),x[2])})}
function Main(o){var comp=new Lampa.InteractionMain(o),timer,last='';function draw(self,quiet){loadRows(quiet).then(function(rows){var sig=JSON.stringify(rows.map(function(r){return[r.title,r.results.map(function(c){return c.yani_id})]}));if(quiet&&sig===last)return;last=sig;self.build(rows);self.render().addClass('anime-lite-v4');if(self.activity&&self.activity.loader)self.activity.loader(false)}).catch(function(e){console.error(e);if(!quiet)note('Не удалось загрузить Anime Lite')})}comp.create=function(){var self=this;if(this.activity&&this.activity.loader)this.activity.loader(true);draw(this,false);timer=setInterval(function(){draw(self,true)},POLL);return this.render()};var destroy=comp.destroy;comp.destroy=function(){if(timer)clearInterval(timer);timer=null;if(destroy)return destroy.apply(this,arguments)};return comp}
function Catalog(o){var comp=new Lampa.InteractionCategory(o);comp.create=function(){var self=this;if(this.activity&&this.activity.loader)this.activity.loader(true);req('/anime?limit=40').then(function(p){self.build({results:arr(p).map(card),total_pages:1,title:o.title||'Каталог'});if(self.activity&&self.activity.loader)self.activity.loader(false)}).catch(function(){note('Каталог недоступен')})};comp.cardRender=function(a,b,c){var api=[a,b,c].filter(function(x){return x&&typeof x.render==='function'})[0],d=[a,b,c].filter(function(x){return x&&x.yani_id})[0];if(api&&d)api.onEnter=function(){openDetail(d)}};return comp}
function openCatalog(title,path){Lampa.Activity.push({url:'anime-lite/'+encodeURIComponent(title),title:title,component:'anime_lite_catalog',page:1,yani_path:path})}
function Genres(o){var comp=new Lampa.InteractionCategory(o);comp.create=function(){var self=this;req('/anime/genres',3600000).then(function(p){var r=root(p),gs=Array.isArray(r)?r:(r&&r.genres)||[];var items=gs.map(function(g){return {title:g.title||g.name||String(g),genre:g}});self.build({results:items,total_pages:1,title:'Жанры'})}).catch(function(){note('Жанры недоступны')})};comp.cardRender=function(a,b,c){var api=[a,b,c].filter(function(x){return x&&typeof x.render==='function'})[0],d=[a,b,c].filter(function(x){return x&&x.genre})[0];if(api&&d)api.onEnter=function(){var g=d.genre,gid=g.id!==undefined?g.id:(g.slug||g.value);openCatalog(d.title,'/anime/genres/'+encodeURIComponent(gid))}};return comp}
function css(){if(document.getElementById('anime-lite-style'))return;var s=document.createElement('style');s.id='anime-lite-style';s.textContent='.anime-lite-v4{background:#0b0d12!important}.anime-lite-v4 .scroll__body{padding-top:1em}.anime-lite-v4 .items-line{margin-bottom:1.65em}.anime-lite-v4 .items-line__title{font-size:1.35em;font-weight:800}.anime-lite-v4 .card__view{border-radius:.8em;overflow:hidden;box-shadow:0 .35em 1.25em rgba(0,0,0,.3)!important}.anime-lite-v4 .card.focus .card__view{outline:.2em solid #fff;outline-offset:.12em;transform:scale(1.04)}.anime-lite-v4,.anime-lite-v4 *{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.anime-lite-v4 .card,.anime-lite-v4 .card__view{transition:transform .1s ease!important}';document.head.appendChild(s)}
function addMenu(text,cls,fn){if(document.querySelector('.'+cls))return;var b=$('<li class="menu__item selector '+cls+'"><div class="menu__text">'+text+'</div></li>');b.on('hover:enter',fn);$('.menu .menu__list').eq(0).append(b)}
function menu(){addMenu('Anime Lite','anime-lite-menu',function(){Lampa.Activity.push({url:'anime-lite',title:'Anime Lite',component:'anime_lite',page:1})});addMenu('Каталог аниме','anime-lite-catalog-menu',function(){openCatalog('Каталог','/anime?limit=40')});addMenu('Жанры аниме','anime-lite-genres-menu',function(){Lampa.Activity.push({url:'anime-lite/genres',title:'Жанры',component:'anime_lite_genres',page:1})})}
function start(){if(window.anime_lite_ready_v4)return;window.anime_lite_ready_v4=true;css();Lampa.Component.add('anime_lite',Main);Lampa.Component.add('anime_lite_catalog',Catalog);Lampa.Component.add('anime_lite_genres',Genres);Lampa.Manifest.plugins={type:'video',version:VERSION,name:'Anime Lite',description:'Современный лёгкий аниме-клиент',component:'anime_lite'};if(window.appready)menu();else Lampa.Listener.follow('app',function(e){if(e.type==='ready')menu()})}
if(window.Lampa)start()})();