(function(){'use strict';
var VERSION='0.2.0',API='https://api.yani.tv',APP='p6_gpujl6d3pho8n';
function req(path){return fetch(API+path,{headers:{'X-Application':APP,Accept:'application/json',Lang:'ru'}}).then(function(r){if(!r.ok)throw Error('API '+r.status);return r.json()})}
function arr(p){var r=p&&p.response?p.response:p;return Array.isArray(r)?r:(r&&(r.anime||r.results||r.items||r.data))||[]}
function v(o,k){for(var i=0;i<k.length;i++){var x=o&&o[k[i]];if(x!==undefined&&x!==null&&x!=='')return x}return ''}
function id(x){return v(x,['anime_id','id','animeId'])}
function title(x){return v(x,['title','title_ru','name','russian','title_en'])||'Без названия'}
function poster(x){var p=v(x,['poster','image','img','cover']);if(p&&typeof p==='object')p=v(p,['huge','mega','big','large','fullsize','full','medium','small','original','url']);p=String(p||'');return p.indexOf('//')===0?'https:'+p:p}
function toCard(x){return {title:title(x),name:title(x),poster:poster(x),img:poster(x),release_date:v(x,['year','release_year']),yani_id:id(x),yani_raw:x}}
function streams(o,out,seen){out=out||[];seen=seen||[];if(o==null)return out;if(typeof o==='string'){if(/^https?:\/\//i.test(o)&&/\.m3u8|\.mp4|\.webm|\.mpd/i.test(o))out.push(o);return out}if(typeof o!=='object'||seen.indexOf(o)>=0)return out;seen.push(o);Object.keys(o).forEach(function(k){streams(o[k],out,seen)});return out.filter(function(x,i,a){return a.indexOf(x)===i})}
function note(s){if(Lampa.Noty)Lampa.Noty.show(s)}
function play(url,name){Lampa.Player.play({url:url,title:name});Lampa.Player.playlist([{url:url,title:name}])}
function open(card){if(!card||!card.yani_id)return;note('Загружаю серии…');req('/anime/'+encodeURIComponent(card.yani_id)+'/videos').then(function(p){var u=streams(p).slice(0,30);if(!u.length)return note('Нет прямого потока для Lampa');var items=u.map(function(x,i){return {title:(i+1)+'. '+(/m3u8/i.test(x)?'HLS':/mp4/i.test(x)?'MP4':'Видео'),url:x}});if(items.length===1)return play(items[0].url,card.title);Lampa.Select.show({title:card.title,items:items,onSelect:function(x){play(x.url,card.title)},onBack:function(){Lampa.Controller.toggle('content')}})}).catch(function(){note('Не удалось загрузить видео')})}
function row(name,items){return {title:name,results:items.map(toCard),nomore:true,card_events:{onEnter:function(target,card){open(card)}}}}
function loadRows(){return Promise.all([req('/anime?limit=12'),req('/anime/schedule'),req('/anime?limit=12&sort=rating')]).then(function(all){var latest=arr(all[0]),schedule=arr(all[1]),top=arr(all[2]);return [row('Новинки',latest),row('Сейчас выходит',schedule.slice(0,12)),row('Популярное',top.length?top:latest.slice().reverse())].filter(function(r){return r.results.length})})}
function Component(object){var comp=new Lampa.InteractionMain(object);comp.create=function(){var self=this;this.activity.loader(true);loadRows().then(function(rows){self.build(rows);self.render().addClass('anime-lite-v2');self.activity.loader(false)}).catch(function(e){console.error('[Anime Lite]',e);self.build([]);self.activity.loader(false);note('Не удалось загрузить Anime Lite')});return this.render()};comp.cardRender=function(a,b,c){var card=null,el=null;[a,b,c].forEach(function(x){if(!x)return;if((x.jquery||x.nodeType)&&!el)el=x;if(x.yani_id&&!card)card=x;var d=x.card||x.object||x.data;if(d&&d.yani_id&&!card)card=d});var n=el&&el.jquery?el[0]:el;if(!card&&n&&n.card_data)card=n.card_data;if(card&&el)$(el).addClass('anime-lite-card')};return comp}
function css(){var s=document.createElement('style');s.id='anime-lite-style';s.textContent='.anime-lite-v2{background:#111!important}.anime-lite-v2 .scroll__body{padding-top:1.2em}.anime-lite-v2 .items-line{margin-bottom:1.4em}.anime-lite-v2 .items-line__title{font-weight:700}.anime-lite-v2 .card__view{box-shadow:none!important}.anime-lite-v2 .card.focus .card__view{outline:.18em solid rgba(255,255,255,.9);outline-offset:.12em;transform:scale(1.025)}.anime-lite-v2,.anime-lite-v2 *{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.anime-lite-v2 .card,.anime-lite-v2 .card__view{transition:none!important}';document.head.appendChild(s)}
function menu(){if(document.querySelector('.anime-lite-menu'))return;var b=$('<li class="menu__item selector anime-lite-menu"><div class="menu__text">Anime Lite</div></li>');b.on('hover:enter',function(){Lampa.Activity.push({url:'anime-lite',title:'Anime Lite',component:'anime_lite',page:1})});$('.menu .menu__list').eq(0).append(b)}
function start(){if(window.anime_lite_ready_v2)return;window.anime_lite_ready_v2=true;css();Lampa.Component.add('anime_lite',Component);Lampa.Manifest.plugins={type:'video',version:VERSION,name:'Anime Lite',description:'Лёгкий Yani-клиент с нативной навигацией Lampa',component:'anime_lite'};if(window.appready)menu();else Lampa.Listener.follow('app',function(e){if(e.type==='ready')menu()})}
if(window.Lampa)start()})();