(function(){'use strict';
var VERSION='0.7.2-quality',API='https://api.yani.tv',APP='p6_gpujl6d3pho8n',POLL=60000,CACHE={};
var PROVIDER_SCORE={anilibria:100,aniliberty:98,animego:94,animelib:92,kodik:86,animevost:82,animedia:78,animebesst:76,dreamerscast:74,mikai:72,moonanime:70,animeon:68};
function req(path,ttl){var c=CACHE[path];if(ttl&&c&&Date.now()-c.at<ttl)return Promise.resolve(c.data);return fetch(API+path,{headers:{'X-Application':APP,Accept:'application/json',Lang:'ru'}}).then(function(r){if(!r.ok)throw Error('API '+r.status);return r.json()}).then(function(x){CACHE[path]={at:Date.now(),data:x};return x})}
function root(p){return p&&p.response!==undefined?p.response:p}function arr(p){var r=root(p);return Array.isArray(r)?r:(r&&(r.anime||r.results||r.items||r.data))||[]}
function val(o,k){for(var i=0;i<k.length;i++){var x=o&&o[k[i]];if(x!==undefined&&x!==null&&x!=='')return x}return ''}
function id(x){return val(x,['anime_id','animeId','id'])||(x&&x.anime&&val(x.anime,['anime_id','id']))}function title(x){return val(x,['title','anime_title','title_ru','name','russian','title_en'])||(x&&x.anime&&title(x.anime))||'Без названия'}
function poster(x){var p=val(x,['poster','image','img','cover']);if(!p&&x&&x.anime)p=poster(x.anime);if(p&&typeof p==='object')p=val(p,['huge','mega','big','large','fullsize','full','medium','small','original','url']);p=String(p||'');return p.indexOf('//')===0?'https:'+p:p}
function statusMeta(x){var st=x&&x.anime_status||x&&x.status||{},alias=String((st&&st.alias)||st||'').toLowerCase(),label=String((st&&st.title)||'');return {alias:alias,label:label}}
function episodeMeta(x){var e=x&&x.episodes||{},aired=Number(e.aired||e.released||x.episodes_aired||0),total=Number(e.count||e.total||x.episodes_count||0),next=Number(e.next_date||x.next_date||0),seasons=Number(x&&x.seasons_count||x&&x.seasons||0),st=statusMeta(x);return {aired:aired,total:total,next:next,seasons:seasons,status:st,label:aired&&total&&aired!==total?aired+'/'+total:(total||aired?String(total||aired):'')}}
function card(x){var p=poster(x),em=episodeMeta(x),typ=val(x,['type','anime_type','kind']);return {title:title(x),name:title(x),poster:p,img:p,release_date:val(x,['year','release_year']),yani_id:id(x),yani_raw:x,yani_episodes:em,yani_type:typ,yani_status:em.status,overview:val(x,['description','synopsis','overview']),vote_average:(x.rating&&x.rating.average)||x.rating||x.score||0}}function note(x){if(Lampa.Noty)Lampa.Noty.show(x)}
function sel(t,items,cb){Lampa.Select.show({title:t,items:items,onSelect:cb,onBack:function(){Lampa.Controller.toggle('content')}})}
function vlist(p){var r=root(p);return Array.isArray(r)?r:(r&&(r.videos||r.items))||[]}function vdata(v){var d=v&&v.data||{};if(typeof d==='string')try{d=JSON.parse(d)}catch(e){d={}}return d||{}}
function voice(v){var d=vdata(v);return d.dubbing||d.translation||d.voice||v.dub_title||v.dubbing||'Без указания озвучки'}function source(v){var d=vdata(v);return d.player||v.player_title||v.player||d.player_id||'Источник'}function ep(v){return String(v.number||v.episode||v.index||v.ep_title||'?')}
function qualityShort(q){q=Number(q)||0;return q>=2160?'4K':q>=1440?'2K':q>=1080?'FHD':q>=720?'HD':q?'SD':''}
function sourceKey(v){return source(v).toLowerCase().replace(/[^a-zа-я0-9]/g,'')}function quality(v){var s=String(v.quality||v.resolution||sourceUrl(v)||''),m=s.match(/(2160|1440|1080|720|576|480|360)/);return m?Number(m[1]):0}
function prefGet(){try{return Lampa.Storage.get('anime_lite_provider','auto')||'auto'}catch(e){return'auto'}}
function prefSet(v){try{Lampa.Storage.set('anime_lite_provider',v)}catch(e){}}
function providerKey(v){var k=sourceKey(v),found='';Object.keys(PROVIDER_SCORE).some(function(p){if(k.indexOf(p)>=0){found=p;return true}});return found||k}
function score(v){var k=sourceKey(v),base=50;Object.keys(PROVIDER_SCORE).forEach(function(p){if(k.indexOf(p)>=0)base=Math.max(base,PROVIDER_SCORE[p])});var q=quality(v);if(q>=1080)base+=8;else if(q>=720)base+=4;if(direct(sourceUrl(v)))base+=10;return base}
function sourceUrl(v){var d=vdata(v);return v.yani_stream_url||v.stream_url||v.file||v.src||v.iframe_url||v.player_url||v.url||v.link||d.yani_stream_url||d.stream_url||d.file||d.src||d.iframe_url||d.player_url||d.url||d.link||''}
function direct(u){return /\.(m3u8|mpd|mp4|webm)(?:[?#].*)?$/i.test(String(u||''))}
function historyGet(){try{return Lampa.Storage.get('anime_lite_history',{})||{}}catch(e){return{}}}
function historyPut(c,v){try{var h=historyGet(),k=String(c.yani_id);h[k]={id:c.yani_id,title:c.title,poster:c.poster||c.img||'',episode:parseFloat(ep(v))||0,source:source(v),at:Date.now()};Lampa.Storage.set('anime_lite_history',h)}catch(e){}}
function playDirect(c,v,u){historyPut(c,v);var item={url:u,title:c.title+' · '+ep(v)+' серия'};Lampa.Player.play(item);Lampa.Player.playlist([item])}
function play(c,v){var u=sourceUrl(v);if(!u)return note('У источника нет ссылки на видео');if(direct(u))return playDirect(c,v,u);if(window.LampaYaniStreamResolver&&LampaYaniStreamResolver.canResolve&&LampaYaniStreamResolver.canResolve(u)){note('Подготавливаю '+source(v)+'…');return LampaYaniStreamResolver.resolve(u,v).then(function(r){if(r&&r.url)return playDirect(c,v,r.url);note('Не удалось получить поток')}).catch(function(){note('Источник «'+source(v)+'» сейчас недоступен')})}note('Источник «'+source(v)+'» не отдаёт прямой поток')}
function autoChoice(a,c){if(!a||!a.length)return null;var max=0;a.forEach(function(v){max=Math.max(max,parseFloat(ep(v))||0)});var watched=c&&historyGet()[String(c.yani_id)],target=watched&&watched.episode<max?watched.episode+1:max,latest=a.filter(function(v){return (parseFloat(ep(v))||0)===target});if(!latest.length)latest=a.filter(function(v){return (parseFloat(ep(v))||0)===max});var pref=prefGet(),preferred=pref==='auto'?[]:latest.filter(function(v){return providerKey(v)===pref||sourceKey(v).indexOf(pref)>=0}),pool=preferred.length?preferred:latest;pool.sort(function(x,y){return score(y)-score(x)});return {video:pool[0],preferred:preferred.length>0,fallback:pref!=='auto'&&!preferred.length,pref:pref}}
function autoLabel(ch){if(!ch||!ch.video)return'';var v=ch.video,q=quality(v),bits=[source(v)];if(q)bits.push(qualityShort(q));bits.push('серия '+ep(v));return bits.join(' · ')}
function autoPlay(c,a){var ch=autoChoice(a,c);if(!ch)return note('Нет доступных серий');var msg='Авто выбрал: '+autoLabel(ch);if(ch.fallback)msg+=' · приоритетный источник недоступен';note(msg);play(c,ch.video)}
function providerSettings(videos){var names={auto:'Авто — лучший доступный',anilibria:'AniLibria',aniliberty:'AniLiberty',animego:'AnimeGo',animelib:'AnimeLib',kodik:'Kodik',animevost:'AnimeVost',animedia:'AniMedia',animebesst:'AnimeBesst',dreamerscast:'Dreamerscast',mikai:'Mikai',moonanime:'MoonAnime',animeon:'AnimeON'},cur=prefGet(),seen={auto:1};(videos||[]).forEach(function(v){var k=providerKey(v);if(k)seen[k]=1});var keys=Object.keys(seen);if(cur!=='auto'&&!seen[cur]){prefSet('auto');cur='auto';note('Сохранённый источник сейчас не найден — включён Авто')};var items=keys.map(function(k){return {title:(k===cur?'✓ ':'')+(names[k]||source((videos||[]).filter(function(v){return providerKey(v)===k})[0])||k),key:k}});sel('Приоритет источника',items,function(x){prefSet(x.key);note('Приоритет: '+(names[x.key]||x.title.replace(/^✓ /,'')))})}
function openVideos(c){note('Ищу доступные источники…');req('/anime/'+encodeURIComponent(c.yani_id)+'/videos').then(function(p){var a=vlist(p);if(!a.length)return note('Для этого аниме пока нет видео');var byVoice={};a.forEach(function(v){var k=voice(v);(byVoice[k]=byVoice[k]||[]).push(v)});var maxEp=0;a.forEach(function(v){maxEp=Math.max(maxEp,parseFloat(ep(v))||0)});var total=c.yani_episodes&&c.yani_episodes.total||0;var preview=autoChoice(a,c),pref=prefGet(),top=[{title:'★ Авто — '+(preview?source(preview.video):'лучший источник'),subtitle:'Последняя серия '+maxEp+(total?' из '+total:'')+(preview&&quality(preview.video)?' · '+qualityShort(quality(preview.video)):'')+(pref!=='auto'?' · приоритет '+pref:''),auto:true},{title:'⚙ Приоритет источника',subtitle:pref==='auto'?'Сейчас: автоматический рейтинг':'Сейчас: '+pref,settings:true}];var voices=Object.keys(byVoice).map(function(k){var x=byVoice[k],providers={};x.forEach(function(v){providers[source(v)]=1});return {title:k,subtitle:Object.keys(providers).length+' источн. · '+x.length+' серий',videos:x}});sel('Смотреть · '+c.title,top.concat(voices),function(ch){if(ch.auto)return autoPlay(c,a);if(ch.settings)return providerSettings(a);var eps={};ch.videos.forEach(function(v){(eps[ep(v)]=eps[ep(v)]||[]).push(v)});var episodes=Object.keys(eps).sort(function(a,b){return parseFloat(a)-parseFloat(b)}).map(function(n){return {title:'Серия '+n,key:n}});sel(ch.title,episodes,function(e){var opts=eps[e.key].slice().sort(function(a,b){return score(b)-score(a)}).map(function(v,i){var q=quality(v);return {title:(i===0?'★ ':'')+source(v),subtitle:(q?qualityShort(q)+' · ':'')+(direct(sourceUrl(v))?'прямой поток':'через resolver')+' · рейтинг '+score(v),video:v}});if(opts.length===1)return play(c,opts[0].video);sel('Серия '+e.key+' · источник',opts,function(o){play(c,o.video)})})})}).catch(function(e){console.error(e);note('Не удалось загрузить видео')})}
function backdrop(d){var p=d&&d.cover||d&&d.backdrop||d&&d.background||'';if(p&&typeof p==='object')p=val(p,['large','huge','big','original','url']);return String(p||'')}
function detailScreen(c,d){var em=episodeMeta(d),sm=statusMeta(d),bg=backdrop(d)||poster(d),desc=String(val(d,['description','overview','summary'])||'').replace(/<[^>]+>/g,' '),genres=(d.genres||[]).map(function(g){return g.title||g.name}).filter(Boolean).slice(0,5).join(' · '),rating=(d.rating&&d.rating.average)||d.rating||d.score||'',year=val(d,['year','release_year']),hist=historyGet()[String(c.yani_id)],wrap=$('<div class="anime-lite-detail"></div>'),hero=$('<div class="anime-lite-hero"></div>');if(bg)hero.css('background-image','linear-gradient(90deg,rgba(8,10,15,.98) 0%,rgba(8,10,15,.78) 46%,rgba(8,10,15,.25) 100%),url("'+bg.replace(/"/g,'')+'")');var info=$('<div class="anime-lite-hero-info"></div>');info.append($('<div class="anime-lite-detail-title"></div>').text(title(d)));var meta=[year,c.yani_type||val(d,['type','kind']),rating?('★ '+rating):'',em.total?((em.aired||0)+'/'+em.total+' сер.'):'',em.seasons?em.seasons+' сез.':'',sm.label||sm.alias].filter(Boolean);info.append($('<div class="anime-lite-detail-meta"></div>').text(meta.join('  •  ')));if(genres)info.append($('<div class="anime-lite-detail-genres"></div>').text(genres));if(desc)info.append($('<div class="anime-lite-detail-desc"></div>').text(desc.slice(0,430)));var buttons=$('<div class="anime-lite-actions"></div>'),watch=$('<div class="anime-lite-action selector">▶ Смотреть</div>'),auto=$('<div class="anime-lite-action selector">★ Авто</div>'),src=$('<div class="anime-lite-action selector">⚙ Источник</div>');if(hist)watch.text('▶ Продолжить · серия '+(hist.episode+1));watch.on('hover:enter',function(){openVideos(c)});auto.on('hover:enter',function(){req('/anime/'+encodeURIComponent(c.yani_id)+'/videos').then(function(v){autoPlay(c,vlist(v))})});src.on('hover:enter',function(){req('/anime/'+encodeURIComponent(c.yani_id)+'/videos').then(function(v){providerSettings(vlist(v))})});buttons.append(watch,auto,src);info.append(buttons);hero.append(info);wrap.append(hero);return wrap}
function openDetail(c){req('/anime/'+encodeURIComponent(c.yani_id),30000).then(function(p){var d=root(p)||c.yani_raw||{};c.yani_episodes=episodeMeta(d);c.yani_type=c.yani_type||val(d,['type','kind']);if(Lampa.Modal&&Lampa.Modal.open){var body=detailScreen(c,d);Lampa.Modal.open({title:'',html:body,size:'full',onBack:function(){Lampa.Modal.close()}});return}var em=episodeMeta(d),items=[{title:'▶ Смотреть',action:'watch'},{title:'★ Авто — последняя серия',action:'auto'}],desc=val(d,['description','overview','summary']),year=val(d,['year','release_year']),sm=statusMeta(d),status=sm.label||sm.alias,rating=(d.rating&&d.rating.average)||d.rating||d.score||'';c.yani_episodes=em;req('/anime/'+encodeURIComponent(c.yani_id)+'/videos',30000).then(function(vp){var ch=autoChoice(vlist(vp),c);if(ch&&ch.video)c.yani_quality=quality(ch.video)}).catch(function(){});if(year||status||rating)items.push({title:[year,status,rating?('★ '+rating):''].filter(Boolean).join(' · ')});if(em.aired||em.total)items.push({title:'Серии: '+(em.aired||0)+(em.total?' из '+em.total:'')});if(em.seasons)items.push({title:'Сезонов: '+em.seasons});if(em.next&&/ongoing|airing|онгоинг/i.test(sm.alias+' '+sm.label))items.push({title:'Следующая серия: '+new Date(em.next*1000).toLocaleDateString('ru-RU')});if(desc)items.push({title:String(desc).replace(/<[^>]+>/g,' ').slice(0,240)});sel(c.title,items,function(x){if(x.action==='watch')openVideos(c);if(x.action==='auto')req('/anime/'+encodeURIComponent(c.yani_id)+'/videos').then(function(v){autoPlay(c,vlist(v))})})}).catch(function(){openVideos(c)})}
function internetPoster(c,img){if(!c||!c.title||!img)return;var key='poster:'+String(c.yani_id||c.title),cached=CACHE[key];if(cached&&cached.data){img.attr('src',cached.data);return}fetch('https://api.jikan.moe/v4/anime?q='+encodeURIComponent(c.title)+'&limit=1').then(function(r){return r.ok?r.json():null}).then(function(p){var a=p&&p.data&&p.data[0],u=a&&a.images&&a.images.jpg&&(a.images.jpg.large_image_url||a.images.jpg.image_url);if(u){CACHE[key]={at:Date.now(),data:u};img.attr('src',u)}}).catch(function(){})}
function decorateCard(el,c){var r=el&&el.jquery?el:$(el||[]),view=r.find('.card__view').first();if(!view.length||view.find('.anime-lite-badges').length)return;var em=c.yani_episodes||{},parts=[],st=em.status||c.yani_status||{},done=em.total>0&&em.aired>=em.total,finished=/finish|complete|released|ended|заверш/i.test((st.alias||'')+' '+(st.label||'')),ongoing=/ongoing|airing|онгоинг|выходит/i.test((st.alias||'')+' '+(st.label||''));if(c.yani_type)parts.push('<span class="anime-lite-badge anime-lite-badge--type">'+String(c.yani_type).toUpperCase()+'</span>');if(em.aired||em.total)parts.push('<span class="anime-lite-badge anime-lite-badge--eps">'+(em.total?(em.aired||0)+'/'+em.total:(em.aired||0))+' сер.</span>');if(finished)parts.push('<span class="anime-lite-badge anime-lite-badge--done">ЗАВЕРШЁН</span>');else if(done)parts.push('<span class="anime-lite-badge anime-lite-badge--done">СЕЗОН ЗАВЕРШЁН</span>');else if(ongoing)parts.push('<span class="anime-lite-badge anime-lite-badge--air">ОНГОИНГ</span>');if(em.seasons>1)parts.push('<span class="anime-lite-badge anime-lite-badge--season">'+em.seasons+' '+(em.seasons<5?'сезона':'сезонов')+'</span>');var aq=c.yani_quality||0;if(aq)parts.push('<span class="anime-lite-badge anime-lite-badge--quality">'+qualityShort(aq)+'</span>');if(c.vote_average)parts.push('<span class="anime-lite-badge anime-lite-badge--rating">★ '+Number(c.vote_average).toFixed(1)+'</span>');if(parts.length)view.append($('<div class="anime-lite-badges">'+parts.join('')+'</div>'));var img=r.find('img').first();if(img.length)img.on('error',function(){var x=$(this);if(!x.data('lite-fallback')){x.data('lite-fallback',1);var raw=c.yani_raw||{},alt=val(raw,['poster_url','image_url','cover_url']);if(alt){x.attr('src',alt);x.one('error',function(){internetPoster(c,x)})}else internetPoster(c,x)}})}
function row(name,items){var seen={};return {title:name,results:(items||[]).map(card).filter(function(c){var k=String(c.yani_id||'');if(!k||seen[k])return false;seen[k]=1;return true}).slice(0,20),nomore:true,card_events:{onEnter:function(t,c){openDetail(c)},onRender:function(t,c){decorateCard(t,c)}}}}
function continueRow(){var h=historyGet(),items=Object.keys(h).map(function(k){return h[k]}).sort(function(a,b){return b.at-a.at}).slice(0,12).map(function(x){return {anime_id:x.id,title:x.title,poster:x.poster,episodes:{aired:x.episode},resume_episode:x.episode}});return items.length?row('Продолжить просмотр',items):null}
function feedRows(feed,catalog,schedule){var f=root(feed)||{},nw=Array.isArray(f.new)?f.new:[],vv=Array.isArray(f.new_videos)?f.new_videos:[],cols=Array.isArray(f.collections)?f.collections:[],latest=vv.map(function(x){return x.anime&&typeof x.anime==='object'?Object.assign({},x.anime,{anime_id:id(x),title:title(x),poster:poster(x)}):x}),rows=[row('Расписание выхода',arr(schedule)),row('Новые релизы',nw.length?nw:catalog),row('Новые переводы',latest)];if(cols.length){var ca=[];cols.forEach(function(x){(x.animes||[]).slice(0,8).forEach(function(a){ca.push(a)})});if(ca.length)rows.push(row('Подборки',ca))}var cr=continueRow();if(cr)rows.unshift(cr);return rows.filter(function(x){return x.results.length})}
function loadRows(fresh){if(fresh){delete CACHE['/feed'];delete CACHE['/anime?limit=20'];delete CACHE['/anime/schedule']}return Promise.all([req('/feed',fresh?0:30000).catch(function(){return {}}),req('/anime?limit=20',fresh?0:30000),req('/anime/schedule',fresh?0:30000)]).then(function(x){return feedRows(x[0],arr(x[1]),x[2])})}
function Main(o){var comp=new Lampa.InteractionMain(o),timer,last='';var nativeCardRender=comp.cardRender;function draw(self,quiet){loadRows(quiet).then(function(rows){var sig=JSON.stringify(rows.map(function(r){return[r.title,r.results.map(function(c){return c.yani_id})]}));if(quiet&&sig===last)return;last=sig;self.build([navRow()].concat(rows));self.render().addClass('anime-lite-v5');if(self.activity&&self.activity.loader)self.activity.loader(false)}).catch(function(e){console.error(e);if(!quiet)note('Не удалось загрузить Anime Lite')})}comp.create=function(){var self=this;if(this.activity&&this.activity.loader)this.activity.loader(true);draw(this,false);timer=setInterval(function(){draw(self,true)},POLL);return this.render()};comp.cardRender=function(){if(nativeCardRender)nativeCardRender.apply(this,arguments);var a=[].slice.call(arguments),el=null,c=null;a.forEach(function(x){if(!x)return;if((x.jquery||x.nodeType)&&!el)el=x;if(x.yani_id&&!c)c=x;var d=x.card||x.object||x.data;if(d&&d.yani_id&&!c)c=d});if(el&&c)decorateCard(el,c)};var destroy=comp.destroy;comp.destroy=function(){if(timer)clearInterval(timer);timer=null;if(destroy)return destroy.apply(this,arguments)};return comp}
function Results(o){var comp=new Lampa.InteractionMain(o);comp.create=function(){var self=this,path=o.yani_path||'/anime?limit=40';if(this.activity&&this.activity.loader)this.activity.loader(true);req(path).then(function(p){self.build([row(o.title||'Результаты',arr(p))]);self.render().addClass('anime-lite-v5');if(self.activity&&self.activity.loader)self.activity.loader(false)}).catch(function(){note('Ничего не найдено')});return this.render()};return comp}
function openResults(t,path){Lampa.Activity.push({url:'anime-lite/results/'+encodeURIComponent(t),title:t,component:'anime_lite_results',page:1,yani_path:path})}
function navRow(){return {title:'Навигация',results:[{title:'⌕ Поиск',lite_action:'search'},{title:'Каталог',lite_action:'catalog'},{title:'Жанры',lite_action:'genres'},{title:'Расписание',lite_action:'schedule'},{title:'⚙ Источник',lite_action:'provider'}],nomore:true,card_events:{onEnter:function(t,c){if(c.lite_action==='search')search();else if(c.lite_action==='catalog')openResults('Каталог','/anime?limit=40');else if(c.lite_action==='genres')genres();else if(c.lite_action==='schedule')openResults('Расписание','/anime/schedule');else if(c.lite_action==='provider')note('Выбор приоритетного источника доступен внутри конкретного аниме')}}}}
function search(){function run(q){q=String(q||'').trim();if(q)openResults('Поиск: '+q,'/anime?q='+encodeURIComponent(q)+'&limit=40')}if(Lampa.Input&&Lampa.Input.edit){Lampa.Input.edit({title:'Поиск аниме',value:''},function(v){run(v)})}else if(Lampa.Input&&Lampa.Input.show){Lampa.Input.show({title:'Поиск аниме'},function(v){run(v)})}else{var q=window.prompt('Поиск аниме');run(q)}}
function genres(){req('/anime/genres',3600000).then(function(p){var r=root(p),gs=Array.isArray(r)?r:(r&&r.genres)||[];sel('Жанры',gs.map(function(g){return {title:g.title||g.name||String(g),genre:g}}),function(x){var g=x.genre,gid=g.id!==undefined?g.id:(g.slug||g.value);openResults(x.title,'/anime/genres/'+encodeURIComponent(gid))})}).catch(function(){note('Жанры недоступны')})}
function css(){if(document.getElementById('anime-lite-style'))return;var s=document.createElement('style');s.id='anime-lite-style';s.textContent='.anime-lite-v5{background:#0b0d12!important}.anime-lite-v5 .scroll__body{padding-top:1em}.anime-lite-v5 .items-line{margin-bottom:1.65em}.anime-lite-v5 .items-line__title{font-size:1.35em;font-weight:800}.anime-lite-v5 .card__view{border-radius:.8em;overflow:hidden;box-shadow:0 .35em 1.25em rgba(0,0,0,.3)!important}.anime-lite-v5 .card.focus .card__view{outline:.2em solid #fff;outline-offset:.12em;transform:scale(1.04)}.anime-lite-v5,.anime-lite-v5 *{backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.anime-lite-v5 .card,.anime-lite-v5 .card__view{transition:transform .1s ease!important}.anime-lite-badges{position:absolute;left:.35em;right:.35em;bottom:.35em;display:flex;gap:.22em;align-items:center;z-index:4;flex-wrap:wrap}.anime-lite-badge{padding:.18em .38em;border-radius:.28em;font-size:.66em;font-weight:800;color:#fff;line-height:1.25;box-shadow:0 .1em .35em rgba(0,0,0,.45)}.anime-lite-badge--type{background:#e11d48}.anime-lite-badge--eps{background:#7c3aed}.anime-lite-badge--air{background:#059669}.anime-lite-badge--done{background:#2563eb}.anime-lite-badge--season{background:#d97706}.anime-lite-badge--quality{background:#0891b2}.anime-lite-badge--rating{background:#111827}.anime-lite-v5 .card__view{aspect-ratio:2/3}.anime-lite-v5 .card__view img{width:100%;height:100%;object-fit:cover}.anime-lite-v5 .card.focus .card__view{outline:.18em solid #fff;outline-offset:.1em;transform:scale(1.035)}.anime-lite-detail{width:88vw;max-width:1500px;min-height:68vh;background:#080a0f;border-radius:1em;overflow:hidden}.anime-lite-hero{min-height:68vh;background-size:cover;background-position:center;display:flex;align-items:flex-end}.anime-lite-hero-info{padding:3.2em;width:58%;text-shadow:0 .12em .35em #000}.anime-lite-detail-title{font-size:2.4em;font-weight:900;margin-bottom:.35em}.anime-lite-detail-meta{font-size:1.05em;font-weight:700;margin-bottom:.7em}.anime-lite-detail-genres{opacity:.8;margin-bottom:.8em}.anime-lite-detail-desc{font-size:1.02em;line-height:1.45;max-height:7em;overflow:hidden}.anime-lite-actions{display:flex;gap:.65em;margin-top:1.4em}.anime-lite-action{padding:.7em 1.05em;border-radius:.55em;background:rgba(255,255,255,.14);font-weight:800}.anime-lite-action.focus{background:#fff;color:#111}.anime-lite-v5 .items-line:first-child .card{width:10em}.anime-lite-v5 .items-line:first-child .card__view{aspect-ratio:2.4/1;border-radius:.65em}';document.head.appendChild(s)}
function addMenu(text,cls,fn){if(document.querySelector('.'+cls))return;var ico='<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="none" stroke="#ffffff" stroke-width="2"/><circle cx="12" cy="12" r="5" fill="none" stroke="#ffffff" stroke-width="1.7"/><path d="M10 8.5 16 12l-6 3.5z" fill="#ffffff"/></svg>';var b=$('<li class="menu__item selector '+cls+'" data-action="anime-lite"><div class="menu__ico">'+ico+'</div><div class="menu__text">'+text+'</div></li>');b.on('hover:enter',fn);$('.menu .menu__list').eq(0).append(b)}
function cleanupMenu(){['anime-lite-search-menu','anime-lite-catalog-menu','anime-lite-genres-menu'].forEach(function(c){$('.'+c).remove()})}function menu(){cleanupMenu();addMenu('Anime Lite','anime-lite-menu',function(){Lampa.Activity.push({url:'anime-lite',title:'Anime Lite',component:'anime_lite',page:1})})}
function start(){if(window.anime_lite_ready_quality)return;window.anime_lite_ready_quality=true;css();Lampa.Component.add('anime_lite',Main);Lampa.Component.add('anime_lite_results',Results);Lampa.Manifest.plugins={type:'video',version:VERSION,name:'Anime Lite',description:'Лёгкий multi-source аниме-клиент',component:'anime_lite',icon:'https://fedot199614.github.io/lampa-anime-lite/icon.svg'};if(window.appready)menu();else Lampa.Listener.follow('app',function(e){if(e.type==='ready')menu()})}
if(window.Lampa)start()})();